// <auto-generated />
using System;
using CodeTestDemo.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeTestDemo.Infrastructure.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20201101044917_MyfirstMigration")]
    partial class MyfirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("CodeTestDemo.Core.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Employee");

                    b.Property<string>("GameTitle");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("TeamA")
                        .HasMaxLength(50);

                    b.Property<int>("TeamAScore");

                    b.Property<string>("TeamB")
                        .HasMaxLength(50);

                    b.Property<int>("TeamBScore");

                    b.HasKey("Id");

                    b.ToTable("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
